name: cameratraps-detector

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.8
  # We pin Pillow to make it as likely as possible that images are loaded via a loader that's identical to the training environment
  - Pillow=9.1.0
  - nb_conda_kernels
  - ipykernel
  - tqdm
  - jsonpickle
  - humanfriendly
  - numpy
  - matplotlib
  - nb_conda_kernels
  - ipykernel
  - opencv
  - requests

  # for running MegaDetector v4
  # - tensorflow>=2.0  

  # for running MegaDetector v5
  - pandas
  - seaborn
  - PyYAML
  - pytorch
  - torchvision
  - cudatoolkit
  - cudnn

# the `nb_conda_kernels` and `ipykernel` packages are installed so that we
# can use Jupyter Notebooks with this environment as a kernel

  # Cropping jpeg lossless
  - cffi
  - libjpeg-turbo
  - pip
  - pip:
    - -e C:/git/jpegtran-cffi
    - pillow-heif
    - PyExifTool